-- Active: 1674225102411@@35.226.146.116@3306@jbl-4416204-felipe-alcantara
CREATE TABLE IF NOT EXISTS PokemonGo(
  id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  Pokedex_Number INT,
  Img_name INT,
  Generation INT,
  Evolution_Stage INT,
  Evolved INT,
  Family_ID INT,
  Cross_Gen INT,
  Type_1 VARCHAR(255),
  Type_2 VARCHAR(255),
  Weather_1 VARCHAR(255),
  Weather_2 VARCHAR(255),
  STAT_TOTAL INT,
  ATK INT,
  DEF INT,
  STA INT,
  Legendary	INT,
  Aquireable INT,
  Spawns INT,
  Regional INT,
  Raidable INT,
  Hatchable INT,
  Shiny INT,
  Nest INT,
  New INT,	
  Not_Gettable INT,	
  Future_Evolve INT,
  100_cp_40 INT,	
  100_cp_39 INT
);